github.com:
    users:
        BearDad:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: BearDad
