github.com:
    users:
        BearDad:
            oauth_token: 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
    git_protocol: https
    user: BearDad
    oauth_token: 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
