github.com:
    users:
        BearDad:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: BearDad
